CREATE TABLE [dbo].[Work]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	[Genre] NVARCHAR(50) NOT NULL,
	[PublicationTime] DATE NOT NULL,
	[Rating] FLOAT NOT NULL,
	[UserId] INT NOT NULL,
	[TextOfWork] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_Work PRIMARY KEY ([Id])
)